# Generated by Django 2.1.7 on 2019-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=256)),
            ],
        ),
    ]
