# Generated by Django 2.1.7 on 2019-05-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dst_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
