# Generated by Django 2.1.7 on 2019-05-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_package_dst_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
