# Generated by Django 2.1.7 on 2019-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_package_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.PositiveIntegerField()),
                ('desti', models.CharField(max_length=25)),
            ],
        ),
    ]
