# Generated by Django 2.1.7 on 2019-05-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.PositiveIntegerField()),
                ('pick', models.CharField(max_length=25)),
                ('drop', models.CharField(max_length=25)),
            ],
        ),
    ]
