# Generated by Django 2.2.5 on 2019-12-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='pick',
        ),
    ]
